# Generated by Django 5.1.1 on 2024-09-05 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchases',
            new_name='Purchase',
        ),
        migrations.RenameModel(
            old_name='RecipeRequirements',
            new_name='RecipeRequirement',
        ),
    ]
