# Generated by Django 5.1.1 on 2024-09-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_purchase_menu_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
