# Generated by Django 5.1.1 on 2024-09-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_reciperequirement_amount_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='total_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
