# Generated by Django 5.1.1 on 2024-09-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_ingredient_total_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='total_value',
            new_name='value',
        ),
    ]
