# Generated by Django 5.1.1 on 2024-09-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_purchase_cost_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
