# Generated by Django 5.1.1 on 2024-09-09 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_purchase_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='menu_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.menuitem'),
        ),
    ]
