# Generated by Django 5.1.1 on 2024-09-09 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_purchase_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='menu_item',
            field=models.ForeignKey(default='Off Menu', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.menuitem'),
        ),
    ]
